# Generated by Django 3.0.3 on 2020-08-27 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_auto_20200814_1420'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='session_token',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
    ]
