# Generated by Django 3.0.3 on 2020-08-27 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_remove_user_session_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='session_token',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
    ]
