# Generated by Django 3.0.3 on 2020-05-05 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budgetitem',
            name='date',
            field=models.DateField(),
        ),
    ]
