# Generated by Django 3.0.3 on 2020-05-05 13:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('budget_app', '0002_auto_20200505_1843'),
    ]

    operations = [
        migrations.AddField(
            model_name='budgetitem',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='budgetitem',
            name='amount',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='budgetitem',
            name='description',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
